import type { ReactNode } from "react";
import styles from "../Lecture.module.css";
import { usePrintMode } from "../printContext";
import { Block, BulletList, Callout, DataTable, Grid, SceneFrame } from "./shared";

const COVER_HINT_LIVE = "Use ← → or the jump menu · DOWNLOAD PDF for a handout";
const COVER_HINT_PRINT = "DDA1000 · Studying at SDS: What and Why";

export function CoverScene() {
  const print = usePrintMode();
  return (
    <section className={`${styles.scene} ${styles.cover}`}>
      <div className={styles.coverInner}>
        <p className={styles.kicker}>Data Science · Financial Engineering · CUHK-Shenzhen</p>
        <h1 className={styles.coverTitle}>From Data to Decisions: What and Why</h1>
        <p className={styles.lead}>
          Before choosing a major or a pathway, it helps to understand how data, models, probability,
          computation, and domain knowledge work together to support reliable decisions under
          uncertainty.
        </p>
        <div className={styles.chips}>
          {["Data", "Models", "Uncertainty", "Risk", "Decisions"].map((chip) => (
            <span key={chip} className={styles.chip}>
              {chip}
            </span>
          ))}
        </div>
        <p className={styles.hint}>{print ? COVER_HINT_PRINT : COVER_HINT_LIVE}</p>
      </div>
    </section>
  );
}

export function ReasonScene() {
  return (
    <SceneFrame kicker="Starting point" title="You chose SDS or FE for a reason">
      <p className={styles.lead}>
        Maybe you are interested in AI, programming, mathematics, finance, markets, business analytics,
        social systems, or simply the idea that data is changing how decisions are made.
      </p>
      <Grid cols={3}>
        <Block title="Interest">
          <p>You already have some curiosity about data, technology, finance, or complex problems.</p>
        </Block>
        <Block title="Uncertainty" tone="blue">
          <p>At the same time, these fields may still feel broad, technical, or even mysterious.</p>
        </Block>
        <Block title="Direction" tone="red">
          <p>Today's goal is to turn vague interest into a clearer understanding of possible paths.</p>
        </Block>
      </Grid>
      <Callout tone="red">
        <p>
          A good university curriculum is not just a list of courses. It is a carefully designed path for
          building judgment under complexity.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function DataToDecisionsScene() {
  return (
    <SceneFrame kicker="Shared foundation" title="From Data to Decisions">
      <p className={styles.lead}>
        Data Science and Financial Engineering share a deep common question: how can we use data, models,
        computation, and theory to make better decisions from imperfect information?
      </p>
      <DataTable
        columns={["Core element", "What it means", "Example questions"]}
        rows={[
          [
            "Data",
            "Observations generated by people, markets, systems, devices, and institutions.",
            "What data do we have? Is it reliable?",
          ],
          [
            "Models",
            "Mathematical, statistical, or computational representations of reality.",
            "Can we predict, explain, price, optimize, or control risk?",
          ],
          [
            "Uncertainty",
            "The future is unknown, data are noisy, and conclusions are never perfect.",
            "How confident should we be? What could go wrong?",
          ],
          [
            "Decisions",
            "Actions based on analysis, with practical and sometimes economic consequences.",
            "What should we do, and what are the risks?",
          ],
        ]}
      />
      <Callout>
        <p>
          The goal is not merely to process data or run models. The goal is to reason carefully and act
          responsibly under uncertainty.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function DeterministicScene() {
  return (
    <SceneFrame kicker="A first level of difficulty" title="Some problems are deterministic">
      <p className={styles.lead}>
        Some problems have clear rules and stable answers. If the inputs and rules are known, the result
        is essentially fixed.
      </p>
      <DataTable
        columns={["Problem type", "Example", "Main challenge"]}
        rows={[
          ["Rule-based calculation", "Calculating interest using a fixed formula", "Applying the rule correctly"],
          ["Database query", "Counting yesterday's transactions", "Retrieving accurate data"],
          ["Basic optimization", "Finding the shortest route on a fixed map", "Computing efficiently"],
        ]}
      />
      <Callout tone="red">
        <p>But many important problems are not deterministic. In reality, we often face uncertainty.</p>
      </Callout>
    </SceneFrame>
  );
}

export function UncertaintyScene() {
  return (
    <SceneFrame kicker="The common environment" title="Most real-world decisions involve uncertainty">
      <p className={styles.lead}>
        We rarely know the future. We usually make decisions based on incomplete, noisy, and imperfect
        data.
      </p>
      <DataTable
        columns={["Field", "Uncertain question"]}
        rows={[
          ["Data Science", "Will this user click? Will this patient recover? Will this model generalize?"],
          ["Financial Engineering", "What is the risk of this portfolio? How should an asset be priced or hedged?"],
          ["Business", "What will demand look like next month?"],
          ["Public systems", "Will this intervention improve outcomes?"],
        ]}
      />
      <Callout>
        <p>
          Uncertainty is not a bug in real-world data. It is the environment in which most important
          decisions are made.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function WorldChangesScene() {
  return (
    <SceneFrame kicker="Non-stationarity" title="When the world changes">
      <p className={styles.lead}>
        In many real systems, the data-generating process changes over time. A model that worked yesterday
        may not work tomorrow.
      </p>
      <DataTable
        columns={["Setting", "What changes?"]}
        rows={[
          ["Consumer behavior", "Preferences shift after new platforms, trends, or products emerge."],
          ["Financial markets", "Volatility, liquidity, correlations, and expectations change over time."],
          ["Macroeconomy", "Inflation, interest rates, policy regimes, and growth conditions evolve."],
          ["AI systems", "User behavior may change after a model is deployed."],
        ]}
      />
      <Callout tone="red">
        <p>
          Historical data are valuable, but they can also be misleading when the world that produced them
          has changed.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function WeakSignalsScene() {
  return (
    <SceneFrame kicker="Modern data challenges" title="High-dimensional data, weak signals">
      <p className={styles.lead}>
        Modern data are often large and high-dimensional, but useful signals may be weak, unstable, or
        hidden behind substantial noise.
      </p>
      <Grid cols={2}>
        <Block title="Data Science examples">
          <BulletList items={["Recommender systems", "Medical imaging", "Social media behavior", "Large-scale user data"]} />
        </Block>
        <Block title="Financial Engineering examples" tone="blue">
          <BulletList items={["Asset returns", "Limit order book data", "Alternative data", "Macroeconomic indicators"]} />
        </Block>
      </Grid>
      <Callout tone="red">
        <p>
          More data does not automatically mean better judgment. The hard question is whether a model is
          finding signal or fitting noise.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function FinanceScene() {
  return (
    <SceneFrame kicker="Financial Engineering" title="Why finance is a special data environment">
      <p className={styles.lead}>
        Finance is a data-rich, uncertainty-heavy, fast-changing environment where decisions have immediate
        economic consequences.
      </p>
      <DataTable
        columns={["Feature", "Why it matters"]}
        rows={[
          ["Markets are forward-looking", "Prices reflect expectations, not only historical facts."],
          ["Data are noisy", "True signals are often weak, unstable, and difficult to verify."],
          ["Systems are adaptive", "Other participants react, learn, and change their behavior."],
          ["Risk is central", "Gains and losses are asymmetric and consequential."],
          ["Decisions are consequential", "Poor models can lead to large losses, unfair outcomes, or systemic risk."],
        ]}
      />
      <Callout>
        <p>
          Financial Engineering combines mathematics, statistics, computing, economics, and risk management
          to support decisions such as pricing, hedging, trading, portfolio construction, and financial risk
          control.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function ConsequencesScene() {
  return (
    <SceneFrame kicker="Decision consequences" title="Models do not end with predictions">
      <p className={styles.lead}>
        A model is not only judged by whether it predicts well. It is also judged by what happens when
        people act on it.
      </p>
      <DataTable
        columns={["Context", "Possible decision", "Consequence of poor judgment"]}
        rows={[
          ["Finance", "Allocate capital, approve credit, hedge risk", "Large losses, unfair lending, or systemic risk"],
          ["Healthcare", "Prioritize patients for treatment", "Delayed care or unequal outcomes"],
          ["Business", "Set prices or recommend products", "Lost revenue or customer distrust"],
          ["Public systems", "Allocate public resources", "Inefficiency or social harm"],
        ]}
      />
      <Callout tone="red">
        <p>
          In high-stakes environments, being approximately right for the wrong reason can still be
          dangerous.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function CurriculumScene() {
  return (
    <SceneFrame kicker="Curriculum design" title="Why does the curriculum look broad?">
      <p className={styles.lead}>
        The curriculum is broad because the problems are broad. Reliable decisions require several kinds
        of knowledge working together.
      </p>
      <DataTable
        columns={["Course area", "What it trains", "Why SDS and FE both need it"]}
        rows={[
          ["Mathematics", "Structure, optimization, dynamics", "Models require precise language."],
          ["Probability and Statistics", "Uncertainty, inference, evidence", "Decisions depend on imperfect data."],
          ["Computer Science", "Algorithms, programming, systems", "Data and models must be implemented."],
          ["Data Science and ML", "Prediction, pattern discovery, evaluation", "Complex data require flexible methods."],
          ["Economics and Finance", "Incentives, markets, value, risk", "Financial decisions need domain logic."],
          ["Ethics and Communication", "Responsibility, explanation, impact", "Results must be used carefully."],
        ]}
      />
      <Callout>
        <p>
          The curriculum is not a collection of unrelated requirements. It is a training system for
          reasoning under uncertainty and complexity.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function AbilitiesScene() {
  return (
    <SceneFrame kicker="Learning outcomes" title="What abilities are we trying to build?">
      <Grid cols={3}>
        <Block title="01 Abstraction">
          <p>Turn messy real-world questions into clear analytical or computational problems.</p>
        </Block>
        <Block title="02 Inference" tone="blue">
          <p>Reason carefully from incomplete, noisy, and sometimes biased data.</p>
        </Block>
        <Block title="03 Computation" tone="red">
          <p>Use programming, algorithms, and systems to work with data effectively.</p>
        </Block>
        <Block title="04 Modeling">
          <p>Build, test, and improve models for prediction, explanation, pricing, or decision support.</p>
        </Block>
        <Block title="05 Risk awareness" tone="blue">
          <p>Understand what can go wrong when data, assumptions, or environments change.</p>
        </Block>
        <Block title="06 Communication" tone="red">
          <p>Explain findings clearly, responsibly, and persuasively to different audiences.</p>
        </Block>
      </Grid>
    </SceneFrame>
  );
}

export function PathsScene() {
  return (
    <SceneFrame kicker="Pathways" title="Different paths, shared foundations">
      <p className={styles.lead}>
        Students may enter different programmes or choose different majors, but these paths share a common
        foundation: modeling, uncertainty, computation, and decision-making.
      </p>
      <DataTable
        columns={["Path", "Central question", "Typical strengths developed"]}
        rows={[
          ["STAT", "Is the conclusion reliable?", "Inference, uncertainty, causality"],
          ["CS&E", "How can we build it efficiently and reliably?", "Algorithms, systems, scalable computing"],
          ["DSBDT", "How can large-scale data be managed and used?", "Data engineering, platforms, applications"],
          ["FE", "How should we price, manage, and act under financial risk?", "Markets, risk, optimization, financial modeling"],
        ]}
      />
      <Callout tone="red">
        <p>
          Choosing a path is not simply asking which label is popular. It is asking which kind of problem
          you want to learn to handle deeply.
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function AskYourselfScene() {
  return (
    <SceneFrame kicker="Self-assessment" title="Ask yourself">
      <div className={styles.split}>
        <div className={styles.stack}>
          <Block title="Do I enjoy asking whether a conclusion is reliable?">
            <p>Look closely at statistics, inference, experiments, and causal reasoning.</p>
          </Block>
          <Block title="Do I enjoy building algorithms, software, or systems?" tone="blue">
            <p>Look closely at computer science, programming, algorithms, and intelligent systems.</p>
          </Block>
          <Block title="Do I enjoy working with large, messy, real-world data?" tone="red">
            <p>Look closely at big data, data engineering, platforms, and applied data projects.</p>
          </Block>
          <Block title="Do I enjoy markets, risk, pricing, and economic consequences?">
            <p>Look closely at financial engineering, risk management, optimization, and financial modeling.</p>
          </Block>
        </div>
        <div>
          <p className={styles.courseTitle}>Pay attention to your learning experience</p>
          <BulletList
            items={[
              "Which problems make you curious?",
              "Which difficult courses are you willing to spend time on?",
              "Where do you feel progress and achievement?",
              "Do you prefer building systems, analyzing evidence, managing data, or reasoning about risk?",
            ]}
          />
          <Callout>
            <p>
              First year is not about labeling yourself too early. It is about observing your interests,
              strengths, and willingness to grow.
            </p>
          </Callout>
        </div>
      </div>
    </SceneFrame>
  );
}

export function ReadyScene() {
  return (
    <SceneFrame kicker="Transition" title="Now we are ready to discuss the pathways">
      <p className={styles.lead}>
        We have seen that data science and financial engineering are both built around a shared challenge:
        making reliable decisions under uncertainty.
      </p>
      <Grid cols={4}>
        <Block title="STAT">
          <p>Reasoning under uncertainty and drawing reliable conclusions from data.</p>
        </Block>
        <Block title="CS&E" tone="blue">
          <p>Building algorithms, systems, and intelligent computational tools.</p>
        </Block>
        <Block title="DSBDT" tone="red">
          <p>Managing, processing, and applying data at scale.</p>
        </Block>
        <Block title="FE">
          <p>Modeling markets, pricing risk, and supporting financial decisions.</p>
        </Block>
      </Grid>
      <Callout tone="red">
        <p>
          The next question is not “Which path is better?” It is “Which direction best matches my
          curiosity, strengths, and future development?”
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function SchoolPackageScene() {
  return (
    <SceneFrame kicker="Shared foundation" title="School Package courses help you discover a major">
      <p className={styles.lead}>
        All SDS Year-1 students take the same school package. These courses are not just requirements —
        they are evidence for which spine you should choose later.
      </p>
      <DataTable
        columns={["Code", "Course"]}
        rows={[
          ["CSC1001/1002 (1003/1004)", "Intro programming plus lab. CS&E students are recommended to take 1003/1004."],
          ["DDA1000", "Freshmen Induction and Academic Planning (1 unit)."],
          ["DDA2001", "Introduction to Data Science."],
          ["MAT1001/1002 (1011/1012), 2041 (2041A)", "Calculus I–II and Linear Algebra. Honours options available."],
          ["PHY1001", "Mechanics."],
          ["STA2001 (2001H)", "Probability and Statistics I. Stat students are recommended to take 2001H."],
        ]}
      />
    </SceneFrame>
  );
}

function PathwayScene({ kicker, title, tagline, points }: { kicker: string; title: string; tagline: string; points: ReactNode[] }) {
  return (
    <SceneFrame kicker={kicker} title={title}>
      <p className={styles.lead}>
        <strong>{tagline}</strong>
      </p>
      <BulletList items={points} />
    </SceneFrame>
  );
}

export function ComputerScienceScene() {
  return (
    <PathwayScene
      kicker="CS&E — Computer Science and Engineering"
      title="Computer Science in the AI era"
      tagline="Build the systems that make AI run."
      points={[
        "Computer Science trains you to design algorithms, software, and computer systems — from data structures and operating systems to how programs actually execute.",
        "In the AI era, models still need people who can implement, scale, debug, and ship them: compilers, databases, operating systems, and large-scale software.",
        "If you enjoy making things run reliably — not only using AI tools — CS&E is the spine for building the infrastructure behind intelligent applications.",
        "AI is one application of CS&E, not a replacement for it. Foundations in algorithms and systems stay useful as models change.",
      ]}
    />
  );
}

export function DataScienceScene() {
  return (
    <PathwayScene
      kicker="DSBDT — Data Science and Big Data Technology"
      title="Data Science in the AI era"
      tagline="Turn data into predictions and decisions."
      points={[
        "Data Science sits between computing and statistics: you learn to collect, model, and deploy data workflows for prediction and decision-making.",
        "In the AI era, DSBDT is the applied path — machine learning, simulation, optimization, and domain data such as finance, operations, and life science.",
        "You practice connecting models to messy real problems: pipelines, evaluation, deployment, and using ML where it actually helps.",
        "If you want to work with AI as a data product — rather than only proving theorems or only writing systems code — DSBDT is designed for that middle ground.",
      ]}
    />
  );
}

export function StatisticsScene() {
  return (
    <PathwayScene
      kicker="STAT — Statistics"
      title="Statistics in the AI era"
      tagline="Choose a way of thinking that stays valid as tools change."
      points={[
        "Statistics trains you to make reliable inferences from limited, noisy data; to quantify uncertainty; and to distinguish correlation from causation.",
        "Tools and models will keep iterating. Probability, inference, and experimental design do not go out of date.",
        "It leads to biostatistics, financial risk, and research, and it also gives a solid foundation for data science and AI.",
        "In an era when AI can answer quickly, statistics helps you ask whether the answer is trustworthy, where bias comes from, and whether a conclusion can survive scrutiny.",
        <>
          STAT and DSBDT are quite close, and to differentiate them a bit, please visit{" "}
          <a href="https://sta-sds.github.io/why_statistics/" target="_blank" rel="noreferrer">
            https://sta-sds.github.io/why_statistics/
          </a>
        </>,
      ]}
    />
  );
}

export function FinancialEngineeringScene() {
  return (
    <PathwayScene
      kicker="FE — Financial Engineering"
      title="Financial Engineering as a pathway"
      tagline="Model markets, measure risk, and support financial decisions."
      points={[
        "Financial Engineering studies how mathematics, statistics, computing, economics, and finance can be used to solve problems in financial markets.",
        "Typical questions include how to price assets, hedge risk, construct portfolios, evaluate credit risk, and design trading or risk management strategies.",
        "FE is especially demanding because financial data are noisy, non-stationary, adaptive, and directly connected to gains, losses, and institutional decisions.",
        "If you are interested in markets, uncertainty, optimization, financial products, and the economic consequences of model-based decisions, FE provides a focused path.",
      ]}
    />
  );
}

export function SpineScene() {
  return (
    <SceneFrame kicker="Takeaways" title="Choose the spine you can sustain">
      <Grid cols={4}>
        <Block title="CS">
          <p>Best when you enjoy serious coding, systems, algorithms, and building reliable software infrastructure.</p>
        </Block>
        <Block title="DS" tone="blue">
          <p>Best for applied ML and multi-domain data work with a moderate theory layer.</p>
        </Block>
        <Block title="STA" tone="red">
          <p>Best for inference, uncertainty, mathematical foundations, and careful evidence-based reasoning.</p>
        </Block>
        <Block title="FE">
          <p>Best for markets, risk, pricing, optimization, and financial decision-making under uncertainty.</p>
        </Block>
      </Grid>
      <Callout tone="red">
        <p>
          In an AI era, many students feel they “should” choose the hottest label. Use Year-1 evidence: what
          you enjoy, what difficulty you can sustain, and which problems you want to handle deeply.{" "}
          <strong>Studying well beats choosing a hot label.</strong>
        </p>
      </Callout>
    </SceneFrame>
  );
}

export function FinalThoughtScene() {
  return (
    <SceneFrame kicker="From curiosity to direction" title="Final thought">
      <p className={styles.lead}>
        Data Science and Financial Engineering are different paths, but they share a demanding intellectual
        habit: using models carefully when the world is uncertain, changing, noisy, and consequential.
      </p>
      <Grid cols={3}>
        <Block title="Learn the foundations">
          <p>Mathematics, statistics, computing, and domain knowledge give you durable tools.</p>
        </Block>
        <Block title="Observe yourself" tone="blue">
          <p>Notice which questions make you curious and which difficulties you are willing to work through.</p>
        </Block>
        <Block title="Build judgment" tone="red">
          <p>The goal is not only technical skill, but reliable decision-making under complexity.</p>
        </Block>
      </Grid>
      <Callout tone="red">
        <p>
          The best path is not the one that sounds most fashionable. It is the one where your curiosity,
          discipline, and long-term growth can meet.
        </p>
      </Callout>
    </SceneFrame>
  );
}
